steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'builder'
  args: 
  - build
  - -t
  - ${_IMAGE}
  - .

- name: 'gcr.io/cloud-builders/docker'
  id: 'pusher'
  args: 
  - push
  - ${_IMAGE}
  waitFor: ['builder']

- name: python
  id: 'installer'
  entrypoint: pip
  args: 
  - install
  - -r
  - requirements.txt
  - --user
  waitFor: ['pusher']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deployer'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - 'final-app'
  - --image
  - ${_IMAGE}
  - --region
  - europe-west1
  - --platform
  - managed
  - --allow-unauthenticated
  - --port
  - '8080'
  - --max-instances
  - '2'
  - --set-env-vars
  - DB_NAME='land_registry_price_paid_uk', DB_USER=$$user, DB_PASS=$$db_pass, CLOUD_SQL_CONNECTION_NAME='$PROJECT_ID:us-west4:test-nuka-cola1'
  secretEnv: ['db_pass', 'user']
  waitFor: ['installer']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/user/versions/latest
    env: user
  - versionName: projects/$PROJECT_ID/secrets/db_pass/versions/latest
    env: db_pass


substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/app

images:
- ${_IMAGE}
