steps:

- name: 'gcr.io/cloud-builders/docker'
  id: 'builder'
  args: 
  - build
  - -t
  - ${_IMAGE}
  - .

- name: 'gcr.io/cloud-builders/docker'
  id: 'pusher'
  args: 
  - push
  - ${_IMAGE}
  waitFor: ['builder']

- name: python
  id: 'installer'
  entrypoint: pip
  args: 
  - install
  - -r
  - requirements.txt
  - --user
  waitFor: ['pusher']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deployer'
  entrypoint: gcloud
  args: 
  - run
  - deploy
  - 'final-app'
  - --image
  - ${_IMAGE}
  - --region
  - europe-west1
  - --platform
  - managed
  - --allow-unauthenticated
  - --port
  - '8080'
  - --max-instances
  - '2'
  env:
  - 'INSTANCE_CONNECTION_NAME=$PROJECT_ID:us-west4:test-nuka-cola1'
  - 'DB_NAME=land_registry_price_paid_uk'
  secretEnv: ['DB_PASS', 'DB_USER']
  waitFor: ['installer']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/user/versions/latest
    env: DB_USER
  - versionName: projects/$PROJECT_ID/secrets/db_pass/versions/latest
    env: DB_PASS


substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/app

images:
- ${_IMAGE}
